title: かっぱ放送局
language: ja
timezone: Asia/Tokyo
description: かっぱのPodcast
description_long: かっぱが日々の生活を話します
url: https://cast.kwappa.net
email: kwappa.856@gmail.com

permalink: /episode/:slug
cdn:
  url: https://cdn.kwappa.net
google_analytics: G-42TYB4K1Q7
hashtag: kwappacast
itunes_podcast_url:
keywords: comma,separated,keywords

markdown: kramdown
sass:
  sass_dir: css
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor

actors:
  kwappa:
    image_url: /images/actors/kwappa.png
    name: kwappa
    url: https://kwappa.net
